Mustache
mcoblenz/Obsidian pull request #316
Opened 2021-04-06 21:26 UTC by ivoysey

this will eventually resolve #310 but it's very much still in progress. i'm making a PR that i will leave as a draft so that it's easy to see what i've done and what's still unimplemented.

2021-04-06 21:32 UTC, mcoblenz requested changes

2021-04-06 21:32 UTC, mcoblenz commented on src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
> +    var tempSymbolTable : Map[String, Int] = Map() // map from field identifiers to index in storage
Scala style guide says no space before colon: https://docs.scala-lang.org/style/types.html

2021-04-06 21:32 UTC, mcoblenz commented on src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
> -        val runtime_obj = YulObject(runtime_name, Code(Block(statement_seq_runtime)), Seq(), Seq())
Scala style guide says to leave these spaces in: https://docs.scala-lang.org/style/method-invocation.html

2021-04-06 21:32 UTC, mcoblenz commented on src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
> +                        Seq(edu.cmu.cs.obsidian.codegen.Switch(sye,Seq(Case(true_lit , Block(pos_yul)), Case(false_lit, Block(neg_yul)))))
also no spaces before commas (https://docs.scala-lang.org/style/method-invocation.html)

2021-04-06 21:32 UTC, mcoblenz commented on src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
> +        var memoryInitRuntime : String = ""
no space here

2021-04-06 21:32 UTC, mcoblenz commented on src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
> +                    print("f is: " + f.toString() + "\n")
Be sure to remove the print before merging.

2021-04-07 23:58 UTC, ivoysey commented
As of the EOD on 7 April, we produce the following Yul for the 4 examples in `GanacheTests`, and ganache accepts all of them (https://travis-ci.com/github/mcoblenz/Obsidian/builds/222454704). (But remember we don't check the output of what Ganache does with what we sent off to it.)

```
object "IfThenElse" {
    code {
            mstore(64, 128)
        return(0, 0)
    }
    object "IfThenElse_deployed" {
        code {
            mstore(64, 128)
                let selector := shr(224, calldataload(0))
                switch selector
                    case 0x70a08231 {
                    }
function ifthenelse(){
        switch true
case true {sstore(0, 1)}
case false {sstore(0, 0)}
        leave
}
            return(0, 0)
        }
    }
}
```
```
object "EmptyContract" {
    code {
            mstore(64, 128)
        return(0, 0)
    }
    object "EmptyContract_deployed" {
        code {
            mstore(64, 128)
            return(0, 0)
        }
    }
}
```
```
object "BoolLiteral" {
    code {
            mstore(64, 128)
        return(0, 0)
    }
    object "BoolLiteral_deployed" {
        code {
            mstore(64, 128)
                let selector := shr(224, calldataload(0))
                switch selector
                    case 0x70a08231 {
                    }
function BoolLiteral(){
        sstore(0, true)
        sstore(0, false)
}
            return(0, 0)
        }
    }
}
```
```
object "IntConst" {
    code {
            mstore(64, 128)
        return(0, 0)
    }
    object "IntConst_deployed" {
        code {
            mstore(64, 128)
                let selector := shr(224, calldataload(0))
                switch selector
                    case 0x70a08231 {
                    }
function intconst(){
        sstore(0, 4)
        leave
}
            return(0, 0)
        }
    }
}
```

2021-04-08 21:48 UTC, ivoysey commented
@mcoblenz this should now be ready for you to review!

2021-04-09 10:51 UTC, ivoysey commented
i made a couple of more changes this morning, but mostly syntactic ones for code clarity. the functionality is the same.

2021-04-09 14:31 UTC, mcoblenz approved these changes

2021-04-09 14:46 UTC, merged